/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SpadeBox {
  constructor(root: string)
  readFile(path: string): Promise<string>
  writeFile(path: string, content: string): Promise<string>
  editFile(path: string, oldString: string, newString: string, replaceAll?: boolean | undefined | null): Promise<string>
}
