/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SpadeBox {
  /**
   * Create a new SpadeBox instance with all tools disabled.
   *
   * Call `enableFiles` to enable filesystem tools and `enableHttp` to enable
   * HTTP fetching.
   */
  constructor()
  /**
   * Enable filesystem tools with `path` as the sandbox root.
   *
   * All file-system operations are restricted to this directory. Returns
   * `this` for chaining. Throws if `path` cannot be opened.
   */
  enableFiles(path: string): this
  /** Returns metadata for all currently enabled tools. */
  tools(): Array<SbTool>
  /**
   * Call a tool by name, passing its parameters as a JSON string (`paramsJson`).
   *
   * Throws a JavaScript exception on protocol errors (unknown tool name or
   * malformed `paramsJson`). Returns a [`SbToolResult`] in all other cases —
   * check `isError` to distinguish tool success from tool-level errors.
   */
  callTool(name: string, paramsJson: string): Promise<SbToolResult>
  /**
   * Read the text content of a file. Calls the `read_file` tool directly.
   *
   * `path` must be relative to the sandbox root (e.g. `'src/main.rs'`).
   * `offset` is a 1-indexed line number to start reading from (default: 1).
   * `limit` caps the number of lines returned.
   * `maxBytes` caps the number of bytes returned (default: 20 000). Pass `0` to disable.
   * Returns the file's content as a UTF-8 string.
   */
  readFile(path: string, offset?: number | undefined | null, limit?: number | undefined | null, maxBytes?: number | undefined | null): Promise<string>
  /**
   * Write text content to a file. Calls the `write_file` tool directly.
   *
   * `path` must be relative to the sandbox root (e.g. `'src/main.rs'`).
   * Creates the file if it does not exist, or overwrites it entirely if it does.
   * If the file already exists, it must be read first — attempting to overwrite
   * without a prior `readFile` call will throw an error.
   * Set `createDirs` to `true` to create any missing intermediate directories
   * automatically. To create a directory without writing a file, end `path`
   * with `'/'` (e.g. `'src/utils/'`) — `content` is ignored in that case.
   */
  writeFile(path: string, content?: string | undefined | null, createDirs?: boolean | undefined | null): Promise<string>
  /**
   * List files matching a glob pattern. Calls the `glob` tool directly.
   *
   * Returns a newline-separated list of relative file paths sorted
   * alphabetically. Use `'**'` to match across directories
   * (e.g. `'**\/*.rs'` finds all Rust files, `'src/**\/*.ts'` finds TypeScript
   * files under `src/`).
   */
  glob(pattern: string): Promise<string>
  /**
   * Search file contents for a regex pattern. Calls the `grep` tool directly.
   *
   * Returns matching lines with their file path and line number.
   * Use `glob` to restrict the search to specific file types
   * (e.g. `'**\/*.rs'`). Use `contextLines` to include N surrounding lines
   * around each match.
   */
  grep(pattern: string, glob?: string | undefined | null, contextLines?: number | undefined | null): Promise<string>
  /**
   * Set the `User-Agent` header sent with every HTTP request.
   *
   * Defaults to `"spadebox/0.0.0 (AI-agent)"`. Returns `this` for chaining.
   *
   * ```js
   * sb.setUserAgent('myagent/1.0').enableHttp().allow('api.example.com', ['GET']);
   * ```
   */
  setUserAgent(userAgent: string): this
  /**
   * Enable HTTP fetching. Returns `this` for chaining with `allow`.
   *
   * ```js
   * sb.enableHttp().allow('api.example.com', ['GET', 'POST']).allow('*.cdn.example.com', ['GET']);
   * ```
   */
  enableHttp(): this
  /**
   * Add a domain rule permitting the given HTTP verbs for `pattern`.
   *
   * `pattern` may be an exact hostname (`"api.example.com"`), a wildcard
   * subdomain (`"*.example.com"`), or a catch-all (`"*"`). When multiple rules
   * match a request, the most specific one wins (longest literal suffix).
   * Returns `this` for chaining.
   *
   * Throws if `pattern` is invalid or any verb is unrecognised.
   */
  allow(pattern: string, verbs: Array<string>): this
  /**
   * Perform an HTTP request and return the response body as text.
   *
   * HTTP must be enabled first via `enableHttp`. The `url` must use the `http`
   * or `https` scheme. `method` is case-insensitive (e.g. `"GET"`, `"POST"`).
   * Pass `body` for methods that send a request body (POST, PUT, PATCH).
   * When `raw` is `false` (default), HTML responses are converted to Markdown.
   * Set `raw` to `true` to receive the raw response body unchanged.
   * `maxBytes` caps the number of bytes returned (default: 20 000). Pass `0` to disable.
   */
  fetch(url: string, method: string, body?: string | undefined | null, raw?: boolean | undefined | null, maxBytes?: number | undefined | null): Promise<string>
  /**
   * Enable the JavaScript tools. Returns `this` for chaining.
   *
   * Once enabled, the JS REPL session persists across calls: variables and functions
   * defined in one `jsRepl` call are available in subsequent ones.
   *
   * ```js
   * const sb = new SpadeBox().enableJs();
   * ```
   */
  enableJs(): this
  /**
   * Evaluate JavaScript code and return the result as a string.
   *
   * The session is persistent: variables and functions defined in one call are
   * available in subsequent calls. Requires `enableJs` to have been called first.
   */
  jsRepl(code: string): Promise<string>
  /**
   * Move or rename a file or directory, or delete it. Calls the `move` tool directly.
   *
   * `src` is the source path relative to the sandbox root. `dst` is the
   * destination path; omit it (pass `null`) when deleting.
   * Set `overwrite` to `true` to replace an existing destination. Set `delete` to `true`
   * (with no `dst`) to delete `src` instead of moving it.
   */
  move(src: string, dst?: string | undefined | null, overwrite?: boolean | undefined | null, del?: boolean | undefined | null): Promise<string>
  /**
   * Replace text within a file. Calls the `edit_file` tool directly.
   *
   * Finds the exact string `oldString` in the file at `path` and replaces it
   * with `newString`. By default `oldString` must appear exactly once —
   * include enough surrounding context to make it unique. Set `replaceAll` to
   * `true` to replace every occurrence instead.
   * Always read the file before editing to ensure `oldString` matches the
   * current content exactly.
   */
  editFile(path: string, oldString: string, newString: string, replaceAll?: boolean | undefined | null): Promise<string>
}

/** Tool metadata exposed to JavaScript. */
export interface SbTool {
  name: string
  description: string
  /** JSON Schema for the tool's parameters, serialized as a JSON string. */
  inputSchema: string
}

/**
 * Result of a tool call.
 *
 * Distinct from a JavaScript exception: a `SbToolResult` is always returned
 * on successful dispatch. Use `isError` to tell the agent whether the tool
 * succeeded or encountered a domain error (e.g. file not found).
 * A JavaScript exception is only thrown for protocol errors (unknown tool
 * name, malformed params JSON) that indicate a developer mistake.
 */
export interface SbToolResult {
  /** `true` when the tool encountered a domain error intended for the agent. */
  isError: boolean
  /** The tool's output (success) or error message (tool-level error). */
  output: string
}
