// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 48401068;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'spadebox_flutter',
    ioDirectory: 'target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiSpadeBoxAddCredential(
      {required SpadeBox that,
      required String name,
      required String value,
      required List<String> domains});

  Future<void> crateApiSpadeBoxAllow(
      {required SpadeBox that,
      required String pattern,
      required List<String> verbs});

  Future<SbToolResult> crateApiSpadeBoxCallTool(
      {required SpadeBox that,
      required String name,
      required String paramsJson});

  Future<String> crateApiSpadeBoxEditFile(
      {required SpadeBox that,
      required String path,
      required String oldString,
      required String newString,
      bool? replaceAll});

  Future<void> crateApiSpadeBoxEnableFiles(
      {required SpadeBox that, required String path});

  Future<void> crateApiSpadeBoxEnableHttp({required SpadeBox that});

  Future<void> crateApiSpadeBoxEnableJs({required SpadeBox that});

  Future<String> crateApiSpadeBoxFetch(
      {required SpadeBox that,
      required String url,
      required String method,
      String? body,
      Map<String, String>? headers,
      bool? raw,
      int? maxBytes});

  Future<String> crateApiSpadeBoxGlob(
      {required SpadeBox that, required String pattern});

  Future<String> crateApiSpadeBoxGrep(
      {required SpadeBox that,
      required String pattern,
      String? glob,
      int? contextLines});

  Future<String> crateApiSpadeBoxJsExec(
      {required SpadeBox that, required String path});

  Future<String> crateApiSpadeBoxJsRepl(
      {required SpadeBox that, required String code});

  Future<String> crateApiSpadeBoxMovePath(
      {required SpadeBox that,
      required String src,
      String? dst,
      bool? overwrite,
      bool? delete,
      bool? createDirs});

  SpadeBox crateApiSpadeBoxNew();

  Future<String> crateApiSpadeBoxReadFile(
      {required SpadeBox that,
      required String path,
      int? offset,
      int? limit,
      int? maxBytes});

  Future<void> crateApiSpadeBoxSetUserAgent(
      {required SpadeBox that, required String userAgent});

  Future<List<SbTool>> crateApiSpadeBoxTools({required SpadeBox that});

  Future<String> crateApiSpadeBoxWriteFile(
      {required SpadeBox that,
      required String path,
      String? content,
      bool? createDirs});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SpadeBox;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SpadeBox;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SpadeBoxPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiSpadeBoxAddCredential(
      {required SpadeBox that,
      required String name,
      required String value,
      required List<String> domains}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(value, serializer);
        sse_encode_list_String(domains, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSpadeBoxAddCredentialConstMeta,
      argValues: [that, name, value, domains],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxAddCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "SpadeBox_add_credential",
        argNames: ["that", "name", "value", "domains"],
      );

  @override
  Future<void> crateApiSpadeBoxAllow(
      {required SpadeBox that,
      required String pattern,
      required List<String> verbs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_list_String(verbs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxAllowConstMeta,
      argValues: [that, pattern, verbs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxAllowConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_allow",
        argNames: ["that", "pattern", "verbs"],
      );

  @override
  Future<SbToolResult> crateApiSpadeBoxCallTool(
      {required SpadeBox that,
      required String name,
      required String paramsJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(paramsJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sb_tool_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxCallToolConstMeta,
      argValues: [that, name, paramsJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxCallToolConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_call_tool",
        argNames: ["that", "name", "paramsJson"],
      );

  @override
  Future<String> crateApiSpadeBoxEditFile(
      {required SpadeBox that,
      required String path,
      required String oldString,
      required String newString,
      bool? replaceAll}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(oldString, serializer);
        sse_encode_String(newString, serializer);
        sse_encode_opt_box_autoadd_bool(replaceAll, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxEditFileConstMeta,
      argValues: [that, path, oldString, newString, replaceAll],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxEditFileConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_edit_file",
        argNames: ["that", "path", "oldString", "newString", "replaceAll"],
      );

  @override
  Future<void> crateApiSpadeBoxEnableFiles(
      {required SpadeBox that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxEnableFilesConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxEnableFilesConstMeta =>
      const TaskConstMeta(
        debugName: "SpadeBox_enable_files",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateApiSpadeBoxEnableHttp({required SpadeBox that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSpadeBoxEnableHttpConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxEnableHttpConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_enable_http",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSpadeBoxEnableJs({required SpadeBox that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSpadeBoxEnableJsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxEnableJsConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_enable_js",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiSpadeBoxFetch(
      {required SpadeBox that,
      required String url,
      required String method,
      String? body,
      Map<String, String>? headers,
      bool? raw,
      int? maxBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(method, serializer);
        sse_encode_opt_String(body, serializer);
        sse_encode_opt_Map_String_String_None(headers, serializer);
        sse_encode_opt_box_autoadd_bool(raw, serializer);
        sse_encode_opt_box_autoadd_u_32(maxBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxFetchConstMeta,
      argValues: [that, url, method, body, headers, raw, maxBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxFetchConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_fetch",
        argNames: [
          "that",
          "url",
          "method",
          "body",
          "headers",
          "raw",
          "maxBytes"
        ],
      );

  @override
  Future<String> crateApiSpadeBoxGlob(
      {required SpadeBox that, required String pattern}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(pattern, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxGlobConstMeta,
      argValues: [that, pattern],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxGlobConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_glob",
        argNames: ["that", "pattern"],
      );

  @override
  Future<String> crateApiSpadeBoxGrep(
      {required SpadeBox that,
      required String pattern,
      String? glob,
      int? contextLines}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_opt_String(glob, serializer);
        sse_encode_opt_box_autoadd_u_32(contextLines, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxGrepConstMeta,
      argValues: [that, pattern, glob, contextLines],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxGrepConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_grep",
        argNames: ["that", "pattern", "glob", "contextLines"],
      );

  @override
  Future<String> crateApiSpadeBoxJsExec(
      {required SpadeBox that, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxJsExecConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxJsExecConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_js_exec",
        argNames: ["that", "path"],
      );

  @override
  Future<String> crateApiSpadeBoxJsRepl(
      {required SpadeBox that, required String code}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(code, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxJsReplConstMeta,
      argValues: [that, code],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxJsReplConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_js_repl",
        argNames: ["that", "code"],
      );

  @override
  Future<String> crateApiSpadeBoxMovePath(
      {required SpadeBox that,
      required String src,
      String? dst,
      bool? overwrite,
      bool? delete,
      bool? createDirs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(src, serializer);
        sse_encode_opt_String(dst, serializer);
        sse_encode_opt_box_autoadd_bool(overwrite, serializer);
        sse_encode_opt_box_autoadd_bool(delete, serializer);
        sse_encode_opt_box_autoadd_bool(createDirs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxMovePathConstMeta,
      argValues: [that, src, dst, overwrite, delete, createDirs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxMovePathConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_move_path",
        argNames: ["that", "src", "dst", "overwrite", "delete", "createDirs"],
      );

  @override
  SpadeBox crateApiSpadeBoxNew() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSpadeBoxNewConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxNewConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_new_",
        argNames: [],
      );

  @override
  Future<String> crateApiSpadeBoxReadFile(
      {required SpadeBox that,
      required String path,
      int? offset,
      int? limit,
      int? maxBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(path, serializer);
        sse_encode_opt_box_autoadd_u_32(offset, serializer);
        sse_encode_opt_box_autoadd_u_32(limit, serializer);
        sse_encode_opt_box_autoadd_u_32(maxBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxReadFileConstMeta,
      argValues: [that, path, offset, limit, maxBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxReadFileConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_read_file",
        argNames: ["that", "path", "offset", "limit", "maxBytes"],
      );

  @override
  Future<void> crateApiSpadeBoxSetUserAgent(
      {required SpadeBox that, required String userAgent}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(userAgent, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSpadeBoxSetUserAgentConstMeta,
      argValues: [that, userAgent],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxSetUserAgentConstMeta =>
      const TaskConstMeta(
        debugName: "SpadeBox_set_user_agent",
        argNames: ["that", "userAgent"],
      );

  @override
  Future<List<SbTool>> crateApiSpadeBoxTools({required SpadeBox that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_sb_tool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSpadeBoxToolsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxToolsConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_tools",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiSpadeBoxWriteFile(
      {required SpadeBox that,
      required String path,
      String? content,
      bool? createDirs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
            that, serializer);
        sse_encode_String(path, serializer);
        sse_encode_opt_String(content, serializer);
        sse_encode_opt_box_autoadd_bool(createDirs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpadeBoxWriteFileConstMeta,
      argValues: [that, path, content, createDirs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpadeBoxWriteFileConstMeta => const TaskConstMeta(
        debugName: "SpadeBox_write_file",
        argNames: ["that", "path", "content", "createDirs"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SpadeBox => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SpadeBox => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SpadeBox
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpadeBoxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SpadeBox
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpadeBoxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(dco_decode_list_record_string_string(raw)
        .map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  SpadeBox
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpadeBoxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<SbTool> dco_decode_list_sb_tool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sb_tool).toList();
  }

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_Map_String_String_None(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  SbTool dco_decode_sb_tool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SbTool(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      inputSchema: dco_decode_String(arr[2]),
    );
  }

  @protected
  SbToolResult dco_decode_sb_tool_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SbToolResult(
      isError: dco_decode_bool(arr[0]),
      output: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SpadeBox
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpadeBoxImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SpadeBox
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpadeBoxImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  SpadeBox
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpadeBoxImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<SbTool> sse_decode_list_sb_tool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SbTool>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sb_tool(deserializer));
    }
    return ans_;
  }

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_Map_String_String_None(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SbTool sse_decode_sb_tool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_inputSchema = sse_decode_String(deserializer);
    return SbTool(
        name: var_name,
        description: var_description,
        inputSchema: var_inputSchema);
  }

  @protected
  SbToolResult sse_decode_sb_tool_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isError = sse_decode_bool(deserializer);
    var var_output = sse_decode_String(deserializer);
    return SbToolResult(isError: var_isError, output: var_output);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          SpadeBox self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SpadeBoxImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          SpadeBox self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SpadeBoxImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
        self.entries.map((e) => (e.key, e.value)).toList(), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpadeBox(
          SpadeBox self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SpadeBoxImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sb_tool(List<SbTool> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sb_tool(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_Map_String_String_None(
      Map<String, String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_Map_String_String_None(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_sb_tool(SbTool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.inputSchema, serializer);
  }

  @protected
  void sse_encode_sb_tool_result(SbToolResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isError, serializer);
    sse_encode_String(self.output, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class SpadeBoxImpl extends RustOpaque implements SpadeBox {
  // Not to be used by end users
  SpadeBoxImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SpadeBoxImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SpadeBox,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SpadeBox,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SpadeBoxPtr,
  );

  /// Register a credential and return an opaque substitution token.
  ///
  /// Pass the returned token as a header value; SpadeBox substitutes the
  /// real credential at fetch time for requests matching `domains`.
  Future<String> addCredential(
          {required String name,
          required String value,
          required List<String> domains}) =>
      RustLib.instance.api.crateApiSpadeBoxAddCredential(
          that: this, name: name, value: value, domains: domains);

  /// Add a domain rule permitting the given HTTP `verbs` for `pattern`.
  ///
  /// `pattern` may be an exact hostname (`"api.example.com"`), a wildcard
  /// subdomain (`"*.example.com"`), or a catch-all (`"*"`).
  /// `verbs` are case-insensitive strings (e.g. `["GET", "POST"]`).
  Future<void> allow({required String pattern, required List<String> verbs}) =>
      RustLib.instance.api
          .crateApiSpadeBoxAllow(that: this, pattern: pattern, verbs: verbs);

  /// Call a tool by name, passing its parameters as a JSON string.
  ///
  /// Throws on protocol errors (unknown tool name, malformed JSON).
  /// Returns an `SbToolResult` in all other cases — check `isError` to
  /// distinguish tool success from tool-level errors.
  Future<SbToolResult> callTool(
          {required String name, required String paramsJson}) =>
      RustLib.instance.api.crateApiSpadeBoxCallTool(
          that: this, name: name, paramsJson: paramsJson);

  /// Replace text within a file.
  ///
  /// Finds the exact string `oldString` and replaces it with `newString`.
  /// Set `replaceAll` to `true` to replace every occurrence.
  Future<String> editFile(
          {required String path,
          required String oldString,
          required String newString,
          bool? replaceAll}) =>
      RustLib.instance.api.crateApiSpadeBoxEditFile(
          that: this,
          path: path,
          oldString: oldString,
          newString: newString,
          replaceAll: replaceAll);

  /// Enable filesystem tools with `path` as the sandbox root.
  ///
  /// All file-system operations are restricted to this directory.
  /// Throws if `path` cannot be opened.
  Future<void> enableFiles({required String path}) =>
      RustLib.instance.api.crateApiSpadeBoxEnableFiles(that: this, path: path);

  /// Enable HTTP fetching. Chain with `allow` to permit specific domains.
  Future<void> enableHttp() => RustLib.instance.api.crateApiSpadeBoxEnableHttp(
        that: this,
      );

  /// Enable the JavaScript runtime tools (jsRepl / jsExec).
  Future<void> enableJs() => RustLib.instance.api.crateApiSpadeBoxEnableJs(
        that: this,
      );

  /// Perform an HTTP request and return the response body as text.
  ///
  /// HTTP must be enabled first via `enableHttp`. `method` is
  /// case-insensitive. HTML responses are converted to Markdown unless
  /// `raw` is `true`.
  Future<String> fetch(
          {required String url,
          required String method,
          String? body,
          Map<String, String>? headers,
          bool? raw,
          int? maxBytes}) =>
      RustLib.instance.api.crateApiSpadeBoxFetch(
          that: this,
          url: url,
          method: method,
          body: body,
          headers: headers,
          raw: raw,
          maxBytes: maxBytes);

  /// List files matching a glob pattern.
  ///
  /// Returns a newline-separated list of relative paths sorted alphabetically.
  Future<String> glob({required String pattern}) =>
      RustLib.instance.api.crateApiSpadeBoxGlob(that: this, pattern: pattern);

  /// Search file contents for a regex pattern.
  ///
  /// Returns matching lines with file path and line number. Use `glob` to
  /// restrict to specific file types (e.g. `"**/*.rs"`).
  Future<String> grep(
          {required String pattern, String? glob, int? contextLines}) =>
      RustLib.instance.api.crateApiSpadeBoxGrep(
          that: this, pattern: pattern, glob: glob, contextLines: contextLines);

  /// Execute a JavaScript file in a fresh runtime.
  ///
  /// `path` is relative to the sandbox root. Each call starts from a clean
  /// context. Requires both `enableJs` and `enableFiles`.
  Future<String> jsExec({required String path}) =>
      RustLib.instance.api.crateApiSpadeBoxJsExec(that: this, path: path);

  /// Evaluate JavaScript code in a persistent session.
  ///
  /// Variables and functions defined in one call are available in subsequent
  /// calls. Requires `enableJs` to have been called first.
  Future<String> jsRepl({required String code}) =>
      RustLib.instance.api.crateApiSpadeBoxJsRepl(that: this, code: code);

  /// Move or rename a file or directory, or delete it.
  ///
  /// `src` is relative to the sandbox root. Pass `dst` to move/rename;
  /// omit it and set `delete` to `true` to delete instead.
  Future<String> movePath(
          {required String src,
          String? dst,
          bool? overwrite,
          bool? delete,
          bool? createDirs}) =>
      RustLib.instance.api.crateApiSpadeBoxMovePath(
          that: this,
          src: src,
          dst: dst,
          overwrite: overwrite,
          delete: delete,
          createDirs: createDirs);

  /// Read the text content of a file.
  ///
  /// `path` is relative to the sandbox root. `offset` is a 1-indexed line
  /// number to start reading from. `limit` caps the number of lines returned.
  /// `maxBytes` caps bytes returned (default 20 000; pass 0 to disable).
  Future<String> readFile(
          {required String path, int? offset, int? limit, int? maxBytes}) =>
      RustLib.instance.api.crateApiSpadeBoxReadFile(
          that: this,
          path: path,
          offset: offset,
          limit: limit,
          maxBytes: maxBytes);

  /// Set the `User-Agent` header sent with every HTTP request.
  Future<void> setUserAgent({required String userAgent}) => RustLib.instance.api
      .crateApiSpadeBoxSetUserAgent(that: this, userAgent: userAgent);

  /// Returns metadata for all currently enabled tools.
  Future<List<SbTool>> tools() => RustLib.instance.api.crateApiSpadeBoxTools(
        that: this,
      );

  /// Write text content to a file.
  ///
  /// `path` is relative to the sandbox root. Creates the file if it does not
  /// exist, or overwrites it entirely if it does. Set `createDirs` to `true`
  /// to create any missing intermediate directories automatically.
  Future<String> writeFile(
          {required String path, String? content, bool? createDirs}) =>
      RustLib.instance.api.crateApiSpadeBoxWriteFile(
          that: this, path: path, content: content, createDirs: createDirs);
}
