// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_anyhow`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpadeBox>>
abstract class SpadeBox implements RustOpaqueInterface {
  /// Register a credential and return an opaque substitution token.
  ///
  /// Pass the returned token as a header value; SpadeBox substitutes the
  /// real credential at fetch time for requests matching `domains`.
  Future<String> addCredential(
      {required String name,
      required String value,
      required List<String> domains});

  /// Add a domain rule permitting the given HTTP `verbs` for `pattern`.
  ///
  /// `pattern` may be an exact hostname (`"api.example.com"`), a wildcard
  /// subdomain (`"*.example.com"`), or a catch-all (`"*"`).
  /// `verbs` are case-insensitive strings (e.g. `["GET", "POST"]`).
  Future<void> allow({required String pattern, required List<String> verbs});

  /// Call a tool by name, passing its parameters as a JSON string.
  ///
  /// Throws on protocol errors (unknown tool name, malformed JSON).
  /// Returns an `SbToolResult` in all other cases — check `isError` to
  /// distinguish tool success from tool-level errors.
  Future<SbToolResult> callTool(
      {required String name, required String paramsJson});

  /// Replace text within a file.
  ///
  /// Finds the exact string `oldString` and replaces it with `newString`.
  /// Set `replaceAll` to `true` to replace every occurrence.
  Future<String> editFile(
      {required String path,
      required String oldString,
      required String newString,
      bool? replaceAll});

  /// Enable filesystem tools with `path` as the sandbox root.
  ///
  /// All file-system operations are restricted to this directory.
  /// Throws if `path` cannot be opened.
  Future<void> enableFiles({required String path});

  /// Enable HTTP fetching. Chain with `allow` to permit specific domains.
  Future<void> enableHttp();

  /// Enable the JavaScript runtime tools (jsRepl / jsExec).
  Future<void> enableJs();

  /// Perform an HTTP request and return the response body as text.
  ///
  /// HTTP must be enabled first via `enableHttp`. `method` is
  /// case-insensitive. HTML responses are converted to Markdown unless
  /// `raw` is `true`.
  Future<String> fetch(
      {required String url,
      required String method,
      String? body,
      Map<String, String>? headers,
      bool? raw,
      int? maxBytes});

  /// List files matching a glob pattern.
  ///
  /// Returns a newline-separated list of relative paths sorted alphabetically.
  Future<String> glob({required String pattern});

  /// Search file contents for a regex pattern.
  ///
  /// Returns matching lines with file path and line number. Use `glob` to
  /// restrict to specific file types (e.g. `"**/*.rs"`).
  Future<String> grep(
      {required String pattern, String? glob, int? contextLines});

  /// Execute a JavaScript file in a fresh runtime.
  ///
  /// `path` is relative to the sandbox root. Each call starts from a clean
  /// context. Requires both `enableJs` and `enableFiles`.
  Future<String> jsExec({required String path});

  /// Evaluate JavaScript code in a persistent session.
  ///
  /// Variables and functions defined in one call are available in subsequent
  /// calls. Requires `enableJs` to have been called first.
  Future<String> jsRepl({required String code});

  /// Move or rename a file or directory, or delete it.
  ///
  /// `src` is relative to the sandbox root. Pass `dst` to move/rename;
  /// omit it and set `delete` to `true` to delete instead.
  Future<String> movePath(
      {required String src,
      String? dst,
      bool? overwrite,
      bool? delete,
      bool? createDirs});

  /// Create a new SpadeBox instance with all tools disabled.
  ///
  /// Call `enableFiles` to enable filesystem tools and `enableHttp` to
  /// enable HTTP fetching.
  static SpadeBox new_() => RustLib.instance.api.crateApiSpadeBoxNew();

  /// Read the text content of a file.
  ///
  /// `path` is relative to the sandbox root. `offset` is a 1-indexed line
  /// number to start reading from. `limit` caps the number of lines returned.
  /// `maxBytes` caps bytes returned (default 20 000; pass 0 to disable).
  Future<String> readFile(
      {required String path, int? offset, int? limit, int? maxBytes});

  /// Set the `User-Agent` header sent with every HTTP request.
  Future<void> setUserAgent({required String userAgent});

  /// Returns metadata for all currently enabled tools.
  Future<List<SbTool>> tools();

  /// Write text content to a file.
  ///
  /// `path` is relative to the sandbox root. Creates the file if it does not
  /// exist, or overwrites it entirely if it does. Set `createDirs` to `true`
  /// to create any missing intermediate directories automatically.
  Future<String> writeFile(
      {required String path, String? content, bool? createDirs});
}

/// Tool metadata.
class SbTool {
  final String name;
  final String description;

  /// JSON Schema for the tool's parameters, serialized as a JSON string.
  final String inputSchema;

  const SbTool({
    required this.name,
    required this.description,
    required this.inputSchema,
  });

  @override
  int get hashCode =>
      name.hashCode ^ description.hashCode ^ inputSchema.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SbTool &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          inputSchema == other.inputSchema;
}

/// Result of a tool call.
///
/// Distinct from a Dart exception: an `SbToolResult` is always returned on
/// successful dispatch. Use `isError` to tell the agent whether the tool
/// succeeded or encountered a domain error (e.g. file not found). A Dart
/// exception (`FrbException`) is only thrown for protocol errors (unknown
/// tool name, malformed params JSON) that indicate a developer mistake.
class SbToolResult {
  /// `true` when the tool encountered a domain error intended for the agent.
  final bool isError;

  /// The tool's output (success) or error message (tool-level error).
  final String output;

  const SbToolResult({
    required this.isError,
    required this.output,
  });

  @override
  int get hashCode => isError.hashCode ^ output.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SbToolResult &&
          runtimeType == other.runtimeType &&
          isError == other.isError &&
          output == other.output;
}
